# Generated by Django 3.2 on 2021-08-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('average_check', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Средний чек, тг')),
                ('average_delivery_time', models.PositiveIntegerField(verbose_name='Среднее время доставки, минут')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'ordering': ('-id',),
            },
        ),
    ]
